Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.box_check_update = false
  config.vm.box_download_insecure=true
  config.vm.network "private_network", ip: "192.168.2.105"
  config.vm.provision "shell", path: "./docker_install.sh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker_ADS17"
    vb.memory = 2048
    vb.cpus = 1
  end	
end