---
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - "FLASK_ENV=development"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
  redis:
    image: "redis:alpine"