services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ".:/app"
    working_dir: /app
  redis:
    image: 'redis:7.0.11-alpine3.17'
    volumes:
      - redis-data:/data
volumes:
  redis-data:
